<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net6.0-windows</TargetFramework><Platforms>AnyCPU;x64</Platforms><PlatformTarget>x64</PlatformTarget></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OmsiLaunch.Api\OmsiLaunch.Api.csproj" />
    <ProjectReference Include="..\..\src\OmsiLaunch.Content\OmsiLaunch.Content.csproj" />
    <ProjectReference Include="..\..\src\OmsiLaunch.Configuration\OmsiLaunch.Configuration.csproj" />
    <ProjectReference Include="..\..\src\OmsiLaunch.Process\OmsiLaunch.Process.csproj" />
    <ProjectReference Include="..\..\src\OmsiLaunch.Core\OmsiLaunch.Core.csproj" />
  </ItemGroup>
</Project>
